gql-dart/ferry

lib/src/client/client.dart
lib/src/widgets/mutation.dart
pubspec.yaml

Add executeOnListen option to responseStream

---

.gitignore
lib/src/client/query_response.dart
test/client/query_response_test.dart

fixed the condition for QueryResponse.hasErrors and added tests for it.
also added the build folder to the gitignore file since it introduced unwanted files which increased the repo size

Fix query response has errors

---

normalize/lib/src/helpers/expand_fragments.dart

Thats what I tried to fix #42. While a quick test was working, other tests are apparently failing. Need to take another look.

Remove the type check for FragmentSpreadNodes in expandFragment

---

normalize/CHANGELOG.md
normalize/pubspec.yaml

bump version

---

ferry/CHANGELOG.md
ferry/pubspec.yaml

bump normalize

---

examples/pokemon_explorer/CHANGELOG.md
examples/pokemon_explorer/lib/src/pokemon_card.dart
examples/pokemon_explorer/lib/src/pokemon_detail.dart
examples/pokemon_explorer/pubspec.yaml
ferry/CHANGELOG.md
ferry/pubspec.yaml
ferry_cache/CHANGELOG.md
ferry_cache/pubspec.yaml
ferry_exec/CHANGELOG.md
ferry_exec/pubspec.yaml
ferry_flutter/CHANGELOG.md
ferry_flutter/pubspec.yaml
ferry_generator/CHANGELOG.md
ferry_generator/pubspec.yaml
ferry_hive_store/CHANGELOG.md
ferry_hive_store/pubspec.yaml
ferry_store/CHANGELOG.md
ferry_store/pubspec.yaml
ferry_test_graphql/CHANGELOG.md
ferry_test_graphql/pubspec.yaml
normalize/CHANGELOG.md
normalize/pubspec.yaml

- ferry@0.10.1
- ferry_cache@0.5.1
- ferry_exec@0.1.1
- ferry_flutter@0.5.1
- ferry_generator@0.4.1
- ferry_hive_store@0.4.1
- ferry_store@0.4.1
- ferry_test_graphql@0.1.1
- normalize@0.5.1
- pokemon_explorer@0.0.1+2

chore(release): publish packages

---

ferry/README.md

Minor correction in the documentation

---

.github/workflows/publish.yml

chore(actions): fix indentation in publish action

---

.github/workflows/publish.yml

chore(actions): add auth to publish workflow

---

.github/workflows/publish.yml
melos.yaml

remove example projects from melos

chore(actions): remove examples from melos

---

.github/workflows/publish.yml

automatically accept prompt from `melos version` command

chore(actions): accept melos version prompt

---

ferry/benchmark/operations.dart
ferry/pubspec.yaml

feat: add benchmarks

---

ferry_cache/pubspec.yaml

moves dependency from devdependencies

fix(cache): move pedantic to dependency

---

ferry/pubspec.yaml

chore(benchmarks): update dependency

---

ferry/lib/src/gql_typed_link.dart
ferry/test/typed_links/gql_typed_link_test.dart
ferry_exec/lib/src/operation_response.dart

feat: add extensions to response

---

ferry_generator/lib/src/req/fragment_req.dart
ferry_generator/lib/src/req/operation_req.dart
ferry_test_graphql/lib/fragments/__generated__/review_fragment.data.gql.dart
ferry_test_graphql/lib/fragments/__generated__/review_fragment.req.gql.dart
ferry_test_graphql/lib/mutations/__generated__/create_review.req.gql.dart
ferry_test_graphql/lib/mutations/__generated__/review_with_date_scalar.req.gql.dart
ferry_test_graphql/lib/queries/__generated__/aliased_hero.req.gql.dart
ferry_test_graphql/lib/queries/__generated__/hero_no_vars.req.gql.dart
ferry_test_graphql/lib/queries/__generated__/hero_with_fragments.data.gql.dart
ferry_test_graphql/lib/queries/__generated__/hero_with_fragments.req.gql.dart
ferry_test_graphql/lib/queries/__generated__/hero_with_inline_fragment.data.gql.dart
ferry_test_graphql/lib/queries/__generated__/hero_with_inline_fragment.req.gql.dart
ferry_test_graphql/lib/queries/__generated__/human_with_args.req.gql.dart
ferry_test_graphql/lib/queries/__generated__/reviews.req.gql.dart

add missing annotations. Partial resolution of #262

fix(ferry_generator): add missing override annotations

---

ferry_exec/pubspec.yaml

fix(ferry_exec): add missing dependencies

---

ferry_generator/pubspec.yaml

fix(ferry_generator): add missing dependencies

---

packages/ferry/lib/ferry.dart
packages/ferry/lib/src/cache_typed_link.dart
packages/ferry/lib/src/fetch_policy_typed_link.dart
packages/ferry/lib/src/request_controller_typed_link.dart
packages/normalize/.gitignore

fix(ferry): add dispose method to TypedLinks

---

.github/workflows/publish.yml

fix github workflow for publishing packages

ops(workflow): fix publishing script

---

.github/workflows/publish.yml

workflow failing because flutter is not present

ops(workflow): enable flutter for publish workflow

---

.github/workflows/publish.yml

ops(workflow): remove dart image from publish workflow

---

.github/workflows/publish.yml

fix missing directory in publish workflow

ops(workflow): fix missing directory in publish workflow

---

.github/workflows/publish.yml

ops(workflow): update publish script

---

docs/flutter-operation-widget.md

Just a one-liner fix in an example.

fix reference to mutation in docs

---

packages/ferry_generator/pubspec.yaml

Add back missing dependency to satisfy pub.dev

chore: add back analyzer dependency

---

.github/workflows/publish.yml

ci: fix ignore publish ferry_test_graphql

ci: fix ignore publish ferry_test_graphql

---

packages/ferry_cache/test/watch_test.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.ast.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.data.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.data.gql.g.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.req.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.req.gql.g.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.var.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/review_by_id.var.gql.g.dart
packages/ferry_test_graphql/lib/queries/review_by_id.graphql
packages/ferry_test_graphql/lib/schema/__generated__/schema.ast.gql.dart
packages/ferry_test_graphql/lib/schema/__generated__/schema.schema.gql.dart
packages/ferry_test_graphql/lib/schema/__generated__/serializers.gql.dart
packages/ferry_test_graphql/lib/schema/__generated__/serializers.gql.g.dart
packages/ferry_test_graphql/lib/schema/schema.graphql

chore(ferry_cache): more tests

chore(ferry_cache): more tests

---

examples/pokemon_explorer/pubspec.yaml

chore(pokemon_explorer): add publish_to: none

chore(pokemon_explorer): add publish_to: none

---

docs/queries.md

docs(website): fix link to built_value

docs(website): fix link to built_value

---

.github/workflows/validate.yml

to bet better understanding why #406 and #407 are failing

ci: update conventional pr dependency

---

.github/workflows/publish.yml

ci: use github-push-action to push back melos version bumps

ci: use github-push-action to push back melos version bumps

---

packages/ferry/test/isolate/isolate_client_test.dart

chore(ferry): cleanup test

---

packages/ferry/test/typed_links/request_controller_typed_link_test.dart

test(ferry): add updateRequest with real client test

test(ferry): add updateRequest with real client test

---

docs/isolates.md

docs(ferry): update docs on how to refetch/paginate with IsolateClient

docs(ferry): update docs on how to refetch/paginate with IsolateClient

---

examples/pokemon_explorer/test/timer_test.dart
packages/ferry/lib/src/fetch_policy_typed_link.dart

Closes https://github.com/gql-dart/ferry/issues/426

refactor: FetchPolicyTypedLink.request() to avoid pending timers in tests

---

examples/pokemon_explorer/ios/Podfile.lock
examples/pokemon_explorer/lib/__generated__/schema.ast.gql.dart
examples/pokemon_explorer/lib/__generated__/schema.schema.gql.dart
examples/pokemon_explorer/lib/__generated__/serializers.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/all_pokemon.ast.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/all_pokemon.data.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/all_pokemon.req.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/all_pokemon.var.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_card_fragment.ast.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_card_fragment.data.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_card_fragment.req.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_card_fragment.var.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_detail.ast.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_detail.data.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_detail.req.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_detail.var.gql.dart
packages/ferry/pubspec.yaml
packages/ferry_generator/pubspec.yaml

allow analyzer 5.0.0
fixes #430

chore(ferry_generator): allow analyzer ^5.0.0

---

.github/workflows/publish.yml
.github/workflows/validate.yml

ci: update action versions

---

examples/pokemon_explorer/lib/__generated__/serializers.gql.g.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/all_pokemon.data.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/all_pokemon.data.gql.g.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_detail.data.gql.dart
examples/pokemon_explorer/lib/src/graphql/__generated__/pokemon_detail.data.gql.g.dart
examples/pokemon_explorer/lib/src/pokemon_list.dart
examples/pokemon_explorer/pubspec.yaml
packages/ferry/CHANGELOG.md
packages/ferry/pubspec.yaml
packages/ferry/test/typed_links/request_controller_typed_link_test.dart
packages/ferry/test/typed_links/update_cache_typed_link_test.dart
packages/ferry_cache/pubspec.yaml
packages/ferry_cache/test/watch_test.dart
packages/ferry_flutter/CHANGELOG.md
packages/ferry_flutter/pubspec.yaml
packages/ferry_generator/pubspec.yaml
packages/ferry_test_graphql/lib/queries/__generated__/aliased_hero.data.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/aliased_hero.data.gql.g.dart
packages/ferry_test_graphql/lib/queries/__generated__/hero_with_fragments.data.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/hero_with_fragments.data.gql.g.dart
packages/ferry_test_graphql/lib/queries/__generated__/human_with_args.data.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/human_with_args.data.gql.g.dart
packages/ferry_test_graphql/lib/queries/__generated__/reviews.data.gql.dart
packages/ferry_test_graphql/lib/queries/__generated__/reviews.data.gql.g.dart
packages/ferry_test_graphql/lib/schema/__generated__/schema.schema.gql.dart
packages/ferry_test_graphql/lib/schema/__generated__/schema.schema.gql.g.dart
packages/ferry_test_graphql/lib/schema/__generated__/serializers.gql.g.dart
packages/ferry_test_graphql/pubspec.yaml
packages/normalize/CHANGELOG.md

fix(ferry_generator)!: properly generate nullable types for nullable elements in Lists

fix(ferry_generator)!: properly generate nullable types for nullable elements in Lists

---

packages/ferry_flutter/pubspec.yaml

chore(ferry_flutter): bump version

---

packages/ferry/lib/ferry_isolate.dart
packages/ferry/lib/src/isolate/isolate_commands.dart

feat(ferry): improve isolate error handling #448

feat(ferry): improve isolate error handling

---

packages/ferry/lib/src/isolate/isolate_commands.dart

fix: when data messages in isolates cannot be send over the isolate, send error to main isolate

fix(ferry): send error to main isolate when data message could not be serialized

---

packages/ferry_cache/lib/src/cache.dart
packages/ferry_cache/test/optimism_test.dart

feat(ferry_cache): add clearOptimisticResponses()

feat(ferry_cache): add `clearOptimisticPatches()`

---

packages/ferry/lib/ferry_isolate.dart
packages/ferry/lib/src/isolate/isolate_commands.dart
packages/ferry/lib/src/isolate/request_response_message.dart
packages/ferry/test/isolate/handle_command_test.dart
packages/ferry/test/isolate/isolate_client_test.dart
packages/ferry/test/typed_links/request_controller_typed_link_test.dart
packages/ferry/test/typed_links/update_cache_typed_link_test.dart
packages/ferry_cache/lib/src/cache.dart
packages/ferry_cache/test/optimism_test.dart
packages/ferry_exec/lib/src/typed_link.dart

- feat(ferry): watch queries/fragments from cache over isolates
- feat(ferry): add clearOptimisticPatches to IsolateClient

feat(ferry): add watchQuery, watchFragment, clearOptimisticPatches to IsolateClient 

---

examples/pokemon_explorer/pubspec.yaml
packages/ferry/CHANGELOG.md
packages/ferry/pubspec.yaml
packages/ferry_cache/CHANGELOG.md
packages/ferry_cache/pubspec.yaml
packages/ferry_flutter/CHANGELOG.md
packages/ferry_flutter/pubspec.yaml

- chore(release): publish packages
- chore(release): publish packages
- chore(release): publish packages
- chore(release): publish packages

chore: publish packages

---

examples/pokemon_explorer/pubspec.yaml
packages/ferry/CHANGELOG.md
packages/ferry/lib/src/gql_typed_link.dart
packages/ferry/pubspec.yaml
packages/ferry_flutter/CHANGELOG.md
packages/ferry_flutter/pubspec.yaml

fix(ferry): add stacktrace to error handler in GqlTypedLink

fix(ferry): add stacktrace to error handler in GqlTypedLink

---

examples/pokemon_explorer/pubspec.yaml
packages/ferry/CHANGELOG.md
packages/ferry/benchmark/operations.dart
packages/ferry/lib/src/isolate/request_response_message.dart
packages/ferry/pubspec.yaml
packages/ferry/test/link_subscription_cancel_test.dart
packages/ferry/test/typed_links/gql_typed_link_test.dart
packages/ferry/test/typed_links/offline_mutation_typed_link_test.dart
packages/ferry/test/typed_links/request_controller_typed_link_test.dart
packages/ferry/test/typed_links/update_cache_typed_link_test.dart
packages/ferry_cache/pubspec.yaml
packages/ferry_exec/pubspec.yaml
packages/ferry_flutter/CHANGELOG.md
packages/ferry_flutter/pubspec.yaml
packages/ferry_generator/CHANGELOG.md
packages/ferry_generator/pubspec.yaml
packages/ferry_test_graphql2/CHANGELOG.md
packages/ferry_test_graphql2/pubspec.yaml

- chore(ferry): fix style issues

chore(ferry): fix style issues

---

packages/ferry_cache/lib/src/fragment_data_change_stream.dart
packages/ferry_cache/lib/src/operation_data_change_stream.dart
packages/ferry_exec/lib/src/operation_response.dart
packages/ferry_exec/lib/src/typed_link.dart
packages/ferry_hive_store/lib/src/hive_store.dart
packages/ferry_store/lib/src/memory_store.dart
packages/normalize/lib/src/utils/field_key.dart
packages/normalize/lib/src/utils/validate_structure.dart

refactor: apply lints fixes

---

packages/ferry_generator/pubspec.yaml

chore: update dependencies

---

docs/cache-configuration.md
packages/ferry/test/field_policy/field_policy_test.dart

docs(ferry): add basic documentation for field policy #494

docs(ferry): add basic documentation for field policy

---

examples/pokemon_explorer/pubspec.yaml
examples/pokemon_explorer/test/dangling_reference_test.dart
packages/ferry/test/client/partial_query_data_test.dart
packages/ferry_cache/lib/src/cache.dart
packages/ferry_cache/lib/src/fragment_data_change_stream.dart
packages/ferry_cache/lib/src/operation_data_change_stream.dart
packages/normalize/lib/src/config/normalization_config.dart
packages/normalize/lib/src/denormalize_fragment.dart
packages/normalize/lib/src/denormalize_node.dart
packages/normalize/lib/src/denormalize_operation.dart
packages/normalize/lib/src/normalize_fragment.dart
packages/normalize/lib/src/normalize_operation.dart
packages/normalize/lib/src/policies/field_policy.dart
packages/normalize/lib/src/utils/exceptions.dart
packages/normalize/lib/src/utils/validate_structure.dart
packages/normalize/test/partial_input_test.dart
packages/normalize/test/partial_results_test.dart

Fixes https://github.com/gql-dart/ferry/issues/498

fix(normalize): Accept partial data in lists

---

.github/workflows/publish.yml
examples/pokemon_explorer/pubspec.yaml
packages/ferry/CHANGELOG.md
packages/ferry/pubspec.yaml
packages/ferry_cache/CHANGELOG.md
packages/ferry_cache/pubspec.yaml
packages/ferry_flutter/pubspec.yaml
packages/normalize/CHANGELOG.md
packages/normalize/pubspec.yaml

- chore(release): publish packages
- ci: always push back changes after publish

ci: always push back changes

---

docs/custom-scalars.md

docs(website): improve custom scalars documention

---

examples/pokemon_explorer/pubspec.yaml
packages/ferry/pubspec.yaml
packages/ferry_exec/pubspec.yaml
packages/ferry_flutter/pubspec.yaml
packages/ferry_generator/pubspec.yaml
packages/ferry_test_graphql2/pubspec.yaml
packages/normalize/pubspec.yaml

feat: support stable 1.0.0 versions of depenencies gql, gql_exec, gql_link

feat: support stable 1.0.0 versions of depenencies gql, gql_exec, gql_link

---

docs/codegen.md
packages/ferry_generator/lib/graphql_builder.dart
packages/ferry_generator/lib/serializer_builder.dart
packages/ferry_generator/lib/src/utils/config.dart
packages/ferry_generator/test/build_test.dart
packages/ferry_generator/test/files/schema.dart

support multiple schemas
where do I write test for this?

feat(ferry_generator): support multiple schemas

---

packages/normalize/lib/src/utils/field_key.dart

chore: fix new lint in normalize

chore: fix new lint

---

packages/ferry_generator/pubspec.yaml

feat(ferry_generator): allow analyzer 6.0

---

docs/isolates.md

docs(ferry): improve documentation around accessing plugins from isolates since Flutter 3.7

---

examples/pokemon_explorer/test/dangling_reference_test.dart
examples/pokemon_explorer/test/timer_test.dart
packages/ferry/lib/src/request_controller_typed_link.dart
packages/ferry/pubspec.yaml
packages/ferry/test/client/json_operation_test.dart
packages/ferry_cache/lib/src/utils/operation_root_data.dart
packages/ferry_cache/pubspec.yaml
packages/ferry_hive_store/pubspec.yaml
packages/ferry_store/pubspec.yaml
packages/ferry_test_graphql2/lib/queries/books.graphql
packages/ferry_test_graphql2/pubspec.yaml
packages/normalize/lib/src/utils/operation_field_names.dart

chore(deps)!: upgrade rxdart to v0.28.0

chore(deps)!: upgrade rxdart to v0.28.0

---

packages/ferry_generator/pubspec.yaml

Hello, please allow using newer analyzer

feat(ferry_generator): allow analyzer 7.3.0

---

packages/ferry_generator/pubspec.yaml

feat(ferry_generator): support analyzer ^7.0.0
