ferry_flutter/lib/src/query.dart
I've detailed the following in an example repository here https://github.com/aaahrens/example_bug.
While wrapping the Query widget with a StreamBuilder it wont update children that use out of scope variables from the builder.
I think this might have something to do with GC or how states are diffed.
Using the builder from the widget and not the state fixes this problem. 
Also: my flutter channel is on dev.
=> Fix for rebuilding outside StreamBuilder

ferry/lib/src/client.dart, ferry/test/error_test.dart, ferry/test/link_subscription_cancel_test.dart
This fixes #51 .
This includes the changes in #52, and fixes for `FetchPolicy.cacheAndNetwork` policy, and extends the test for canceling the streams when they are not listened to anymore for all FetchPolicies.
I am not really sure why these fixes to `FetchPolicy.cacheAndNetwork` are necessary, I know too little about rxdart for this. But with wrapping the network stream in a new StreamController and manually canceling it, the canceling of the stream is passed on the Link, too.
There might be a better with rxdart, which is why I put this fix in a separate PR.
=> Fix stream cancelling for FetchPolicy.CacheAndNetwork, too

ferry/CHANGELOG.md, ferry/pubspec.yaml, normalize/CHANGELOG.md, normalize/lib/src/policies/type_policy.dart, normalize/lib/src/utils/exceptions.dart, normalize/lib/src/utils/resolve_data_id.dart, normalize/pubspec.yaml, normalize/test/type_policy/key_fields_test.dart
This PR refactors the TypePolicy.keyFIelds API. It now accepts a Map of fields (and subfields) and can be used like this:
```dart
final typePolicies = {
'Post': TypePolicy(
keyFields: {
'id': true,
'title': true,
'author': {
'name': true,
},
},
)
};
```
Any values other than `true` will be ignored.
=> Refactor TypePolicy.keyFields to allow for child keyFields

ferry/lib/src/client.dart, ferry/test/plugins/plugins_list_mutation_test.dart
Currently, the reference to the list of `plugins` of a client is a reference to the global `defaultPlugins` variable by default.
This means, mutating this list also mutates the `defaultPlugins` variable.
This is probably unexpected behavior for most users.
I would assume, that if I created 2 clients and mutate the list of plugins of one client, that this has no effect on the second client.
This PR changes this behavior, the client now copies its `plugins` list from `defaultPlugins` and adds a test that verifies this.
=> Copy list of Plugins from defaultPlugins when instantiating a client

normalize/lib/src/config/normalization_config.dart, normalize/lib/src/denormalize_fragment.dart, normalize/lib/src/denormalize_node.dart, normalize/lib/src/denormalize_operation.dart, normalize/lib/src/normalize_fragment.dart, normalize/lib/src/normalize_node.dart, normalize/lib/src/normalize_operation.dart, normalize/lib/src/policies/field_policy.dart, normalize/lib/src/utils/exceptions.dart, normalize/lib/src/utils/resolve_data_id.dart, normalize/lib/src/utils/validate_structure.dart, normalize/lib/utils.dart, normalize/test/partial_input_test.dart
* Adds a `path` to `PartialDataException` to surface invalid paths
* Adds `acceptPartialData=true` to `normalizeFragment` and `normalizeOperation`
to allow for the rejection of structurally incomplete results (i.e. `{}` != '{ foo: null }')
* `denormalizeFragment` and `denormalizeOperation` now have a `handleException=true` flag which can be disabled to throw rather than return null
* Adds a `validateOperationDataStructure` closing #102 (`handleException=false` by default)
* moved `returnPartialData` to `config.allowPartialData` in `denormalizeNode` as partial data is now a cross cutting concern
* add tests and a few docstrings elsewhere
=> More robust partial data handling

normalize/CHANGELOG.md, normalize/pubspec.yaml
I published the changes from #104 `0.4.3-alpha` just so I could move ahead with #754 without publishing with a git dependency
=> update changelog with #104

ferry/lib/src/fetch_policy_typed_link.dart, ferry/test/typed_links/fetch_policy_typed_link_test.dart
On my last PR I included an ugly hack that created a new `StreamController` for each new request `FetchPolicy.CachAndNetwork.`
I did not know why it was required, but the stream did not properly cancel otherwise.
I just read about a fixed memory leak in rxdart 0.25, and immediately thought of this issue.
Turns out, that really was the problem.
With rxdart 0.25.0, this workaround is no longer required (I verified it by downgrading back to 0.24 - link_subscription_cancel_test fails on 0.24, but not on 0.25 when the workaround is removed).
However, now another test failed:
CacheAndNetwork returns correct data now got a network response when it expected a cached response. But this was fixed the adding a delay of 0 milliseconds to the mocked network response (could this be solved in a more …
=> remove workaround for rxdart memory leak

ferry/CHANGELOG.md, ferry/lib/ferry.dart, ferry/lib/src/error_typed_link.dart, ferry/pubspec.yaml, ferry/test/typed_links/error_typed_link_test.dart, ferry_exec/CHANGELOG.md, ferry_exec/lib/ferry_exec.dart, ferry_exec/lib/src/exceptions.dart, ferry_exec/pubspec.yaml, ferry_flutter/CHANGELOG.md, ferry_flutter/lib/src/operation.dart, ferry_flutter/pubspec.yaml
This PR improves the default error handling behavior in the following ways:
1. `ErrorTypedLink` now catches `Stream.error` events and converts them into `OperationResponse`s with a `linkException` property.
2. `ErrorTypedLink` now catches sync errors when forwarding the request in the TypedLink chain and converts them into `OperationResponse`s with a `linkException` property.
3. `ferry_flutter`'s `OperationResponseBuilder` now includes any errors from the underlying `StreamBuilder`
=> Improve default error handling

ferry_cache/lib/src/cache.dart, ferry_cache/lib/src/fragment_data_change_stream.dart, ferry_cache/lib/src/operation_data_change_stream.dart, ferry_cache/test/data_change_streams_test.dart, ferry_cache/test/sync_operations_test.dart, normalize/lib/src/denormalize_fragment.dart, normalize/test/fragments_test.dart
This attempts to fix #187 with minimal changes.
I wrote some simple tests, but happy to build out more complex test cases if necessary, normalize seemed to test this functionality pretty well already.
=> Add support for dataIdFromObject to ferry_cache and swap the order of assignment in denormalize_fragment

ferry_cache/lib/src/cache.dart, ferry_cache/lib/src/operation_data_change_stream.dart, ferry_cache/lib/src/utils/operation_root_data.dart, ferry_cache/test/data_change_streams_test.dart, normalize/lib/src/config/normalization_config.dart, normalize/lib/src/denormalize_fragment.dart, normalize/lib/src/denormalize_node.dart, normalize/lib/src/denormalize_operation.dart, normalize/lib/src/normalize_fragment.dart, normalize/lib/src/normalize_node.dart, normalize/lib/src/normalize_operation.dart, normalize/lib/src/policies/field_policy.dart, normalize/lib/src/utils/expand_fragments.dart, normalize/lib/src/utils/operation_field_names.dart, normalize/test/possible_type_of.dart
This PR adds improved support for fragment resolution by introducing a new map to lookup type relationship
Take the document: 
```graphql
fragment FAuthor on Author {
__typename
id
}
fragment FAudience on Audience {
__typename
id
numHands
isClapping
}
fragment FUser on User {
id
__typename
name
}
query {
users {
...FAuthor
...FAudience
...FUser
}
}
```
and the schema 
```graphql
type Query {
users: [User]
}
interface User { 
id: ID!
name: String
}
type Author implements User {
id: ID!
name: String
numBooks: Int
}
type Audience implements User {
id: ID!
name: String
numHands: Int
isClapping: Boolean
}
```
the current implementation will fail to realize which fragment spreads apply to a given type. E.g. that `FUser` and `FAuthor` should apply to the `Author` type. This leads to partial …
=> feat: Add support for better fragment type resolution

examples/pokemon_explorer/CHANGELOG.md, examples/pokemon_explorer/pubspec.yaml, ferry/CHANGELOG.md, ferry/pubspec.yaml, ferry_cache/CHANGELOG.md, ferry_cache/pubspec.yaml, ferry_exec/CHANGELOG.md, ferry_exec/pubspec.yaml, ferry_flutter/CHANGELOG.md, ferry_flutter/pubspec.yaml, ferry_generator/CHANGELOG.md, ferry_generator/pubspec.yaml, ferry_hive_store/CHANGELOG.md, ferry_hive_store/pubspec.yaml, ferry_store/CHANGELOG.md, ferry_store/pubspec.yaml, ferry_test_graphql/CHANGELOG.md, ferry_test_graphql/pubspec.yaml, normalize/CHANGELOG.md, normalize/lib/src/utils/expand_fragments.dart, normalize/pubspec.yaml, normalize/test/query_fragments/named_fragments_test.dart
The recent changes to allow `possibleTypes` broke the ability to use inline fragments on interfaces and unions without providing a `possibleTypes` map. This PR reverts those changes for inline fragments.
=> Revert possible types changes for inline fragments

.github/workflows/commits.yml, CONTRIBUTING.md
Enforces [Conventional PRs](https://github.com/marketplace/actions/conventional-prs) via github action.
=> chore: enforce conventional commits

packages/ferry/benchmark/operations.dart, packages/ferry/pubspec.yaml, packages/ferry/test/link_subscription_cancel_test.dart, packages/ferry/test/typed_links/fetch_policy_typed_link_test.dart, packages/ferry/test/typed_links/gql_typed_link_test.dart, packages/ferry/test/typed_links/update_cache_typed_link_test.dart, packages/ferry_exec/pubspec.yaml, packages/ferry_flutter/pubspec.yaml, packages/ferry_generator/pubspec.yaml, packages/ferry_test_graphql/lib/fragments/__generated__/review_fragment.data.gql.dart, packages/ferry_test_graphql/lib/queries/__generated__/hero_with_fragments.data.gql.dart, packages/ferry_test_graphql/lib/queries/__generated__/hero_with_inline_fragment.data.gql.dart, packages/ferry_test_graphql/pubspec.yaml
Current Problem:
Ferry generator isn't compatible with a lot of updated generator packages because of this old analyzer entry.
Example output: 
```
Because auto_route_generator 3.2.3 depends on analyzer >=2.7.0 <4.0.0 and ferry_generator >=0.5.0-dev.5 depends on analyzer ^1.7.2, auto_route_generator 3.2.3 is incompatible with ferry_generator >=0.5.0-dev.5.
So, because app depends on both ferry_generator ^0.5.0-dev.9 and auto_route_generator 3.2.3, version solving failed.
pub get failed (1; So, because app depends on both ferry_generator ^0.5.0-dev.9 and auto_route_generator 3.2.3, version solving failed.)
```
It looks like the analyzer entry is vestigial since `dart analyze` does not require to be added as a library.
Solution:
* Delete the entry
* Update existing deps gql_code_builder and …
=> fix: remove analyzer from ferry_generator

packages/ferry/lib/src/request_controller_typed_link.dart, packages/ferry/test/typed_links/request_controller_typed_link_test.dart
Updated logic in RequestControllerTypedLink to check the stream for the same instance, rather than equivalent, requests.  This was creating duplicate network requests if the a new request was created with the same parameters that had been issued previously.  This affects both queries and mutations.
This addresses the issue in #341
=> Updated RequestController duplciate request logic

packages/normalize/lib/src/normalize_node.dart
Fixing this error:
```
E/flutter (20393): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter (20393): #0      normalizeNode (package:normalize/src/normalize_node.dart:41:25)
E/flutter (20393): #1      normalizeNode.<anonymous closure> (package:normalize/src/normalize_node.dart:90:29)
E/flutter (20393): #2      ListMixin.fold (dart:collection/list.dart:237:22)
E/flutter (20393): #3      normalizeNode (package:normalize/src/normalize_node.dart:60:19)
E/flutter (20393): #4      normalizeOperation (package:normalize/src/normalize_operation.dart:68:5)
E/flutter (20393): #5      NormalizingDataProxy.writeQuery …
```
=> fix cast error

packages/normalize/lib/src/denormalize_fragment.dart, packages/normalize/lib/src/denormalize_operation.dart, packages/normalize/lib/src/normalize_fragment.dart, packages/normalize/lib/src/normalize_node.dart, packages/normalize/lib/src/normalize_operation.dart, packages/normalize/lib/src/utils/constants.dart, packages/normalize/lib/src/utils/get_fragment_map.dart, packages/normalize/lib/src/utils/identify.dart, packages/normalize/lib/src/utils/reachable_ids.dart, packages/normalize/lib/src/utils/resolve_data_id.dart, packages/normalize/lib/src/utils/resolve_root_typename.dart, packages/normalize/lib/src/utils/validate_structure.dart, packages/normalize/test/root_type_test.dart
This PR streamlines how `dataId`'s are resolved throughout the normalization. Right now operation types are handled specially for operations, but not for fragments, or nested fields with the same type.
Assume we have the schema
```graphql
type Query {
query: Query
name: String
}
```
then normalizing the fragment
```graphql
fragment F on Query {
__typename
name
}
```
will throw an error unless a custom `dataIdFromObject` is specified. This while the above can be normalized just as easily as
```graphql
query Q {
__typename
name
}
```
Furthermore, this problem is also present with fields having the operation type as their type. Take the query
```graphql
Mutation Q2 {
__typename
q { name __typename }
}
```
normalizing this should yield
```json
{"query": {"__typename": "Query", "name": "Bob", …
```
=> fix: Streamline typename handling

packages/ferry_generator/lib/src/utils/locations.dart
This solves the problem that on Windows the import paths are created with backslash, which makes the import corrupt.
Solution is from @axrs, see https://github.com/gql-dart/ferry/issues/298#issuecomment-1009613691.
This closes #298 and closes #316.
To use it add the following to `pubspec.yaml`:
```yaml
dependencies:
ferry_generator:
git:
url: https://github.com/friebetill/ferry.git
path: packages/ferry_generator/
dependency_overrides:
ferry_generator:
git:
url: https://github.com/friebetill/ferry.git
path: packages/ferry_generator/
```
=> fix: Use Posix separators for output paths

packages/normalize/lib/src/denormalize_operation.dart, packages/normalize/lib/src/normalize_operation.dart
This change will ensure backward compatibility by defaulting the typename to the `rootTypeName` when we can't resolve the data ID for a root object. 
After some consideration, I believe this is a better implementation. We HAVE to write the root objects otherwise no nested objects will be saved.
This, I believe, also means that we can release this as a minor change.
=> fix: Preserve backwards compatibility

packages/ferry_cache/lib/src/cache.dart, packages/ferry_cache/lib/src/fragment_data_change_stream.dart, packages/ferry_cache/lib/src/operation_data_change_stream.dart, packages/ferry_cache/test/test/data_change_streams_test.dart
normalize now requires possibleTypes in order to deal with fragments, unions, and interfaces. 
these possibleTypes were not correctly passed from the cache to normalize in some scenarios.
=> fix: add possibleTypes to every function that can use it of normalize

packages/ferry_cache/lib/src/cache.dart
The issue was caused by this line: https://github.com/gql-dart/ferry/blob/201980f313a98aa94ef45146ff229f24a95c3125/packages/ferry_cache/lib/src/cache.dart#L105
As per the [docs](https://api.flutter.dev/flutter/dart-async/Stream/isEmpty.html), isEmpty `waits for the first element of this stream`. The problem is that `operationDataChangeStream` and `fragmentDataChangeStream` end with `.skip(1)` so the stream never emits and the Future is pending forever.
My fix seems extremely simple, so maybe I missed some complexity but all the tests are passing...
Also, I don't know how to write an additional test to make sure that we don't leak.
If you want to manual test, I've created a branch where I added the original memory-leak repo: https://github.com/GP4cK/ferry/tree/memory-leak-example (it …
=> fix(cache): Fix memory leak.

packages/ferry_cache/lib/src/fragment_data_change_stream.dart, packages/ferry_cache/lib/src/operation_data_change_stream.dart, packages/ferry_cache/test/test/data_change_streams_test.dart, packages/ferry_cache/test/watch_test.dart
@knaeckeKami this is an alternative to https://github.com/gql-dart/ferry/pull/401/files to fix the regression in the watch method based on your todo:
```dart
// todo: refactor operationDataChangeStream / fragmentChangeDataStream so that they can
// deal with added ids, so we don't have to maintain this ugly block below
```
I've only modified the `operationDataChangeStream` for now to test the idea with you. I would need to update the `fragmentDataChangeStream` too before this gets merged.
~~The issue that I have though is that in the tests, [we are expecting the watchQuery() to emit a done event](https://github.com/gql-dart/ferry/blob/0c3cccc787d85135f2189a670d485614a5cf51fa/packages/ferry_cache/test/watch_test.dart#L163) but this implementation doesn't. If we comment the line, the test …
=> fix(ferry_cache): fix regression in watch() methods by making changeStream emit when new item is added to the cache

packages/ferry_cache/lib/src/fragment_data_change_stream.dart, packages/ferry_cache/lib/src/operation_data_change_stream.dart
In one of the later PR, we changed operationChangeDataStream() and fragmentChangeDataStream() to watch for changed data ids.
There was a mistake though, we used MapEquality to filter updates, but the maps we compare can contain other maps.
MapEquality only works for flat maps.
see
```dart
import 'package:collection/collection.dart';
void main() {
print(const MapEquality().equals({"a" : 1}, {"a" : 1}));
print(const MapEquality().equals({"a" : {}}, {"a" : {}}));
}
```
this PR changes the comparison back to DeepCollectionEquality, as the current behaviour caused many duplicate updates from the cache on every query
might fix #394 
cc @GP4cK
=> fix(ferry_cache): fix cache emits update too often

packages/ferry/lib/ferry_isolate.dart, packages/ferry/lib/src/isolate/handle_command.dart, packages/ferry/lib/src/isolate/isolate_commands.dart, packages/ferry/test/isolate/handle_command_test.dart, packages/ferry/test/isolate/isolate_client_test.dart
feat(ferry): add removeOptimisticResponse to isolate client
=> feat(ferry): add removeOptimisticResponse to isolate client

packages/ferry/test/typed_links/request_controller_typed_link_test.dart, packages/ferry_cache/lib/src/cache.dart, packages/ferry_cache/test/watch_test.dart, packages/ferry_exec/lib/src/typed_link.dart
… in cache in watchQuery/watchFragment
fixes #415 
also related
#394
=> fix(ferry_cache): ensure only emitting one update per updated data ID

docs/mutations.md
Fix a possible typo in the beginning of line 126, from "If Ferry,..." to "In Ferry,...".
=> docs(website): fix typo in mutations.md

packages/normalize/lib/src/denormalize_node.dart, packages/normalize/lib/src/normalize_node.dart, packages/normalize/lib/src/utils/expand_fragments.dart, packages/normalize/lib/src/utils/operation_field_names.dart, packages/normalize/lib/src/utils/well_known_directives.dart, packages/normalize/test/partial_results_test.dart, packages/normalize/test/utils/expand_fragment_test.dart, packages/normalize/test/utils/is_skipped_test.dart
When checking for partial data, do not treat missing fields as partial data, if the field has a `skip` directive with an `if:` argument that evaluates to `true` or an `include` directive with an `if:` argument that evaluates to `false`
or if the field is in a fragment or an inline fragment with such a directive
fixes #432
=> feat(normalize)!: respect skip/include directives when checking for partial data

packages/ferry/lib/src/fetch_policy_typed_link.dart, packages/ferry/test/typed_links/fetch_policy_typed_link_test.dart
- fix(ferry)!: remove optimistic patch when listener unsubscribes before link responds with data instead of leaking optimistic patch forever
=> fix(ferry)!: remove optimistic patch when listener unsubscribes before link responds with data instead of leaking optimistic patch forever

examples/auth_token_with_isolate/client/macos/Flutter/GeneratedPluginRegistrant.swift, packages/ferry_cache/lib/src/utils/json_equals.dart, packages/ferry_hive_store/lib/src/hive_store.dart, packages/ferry_store/lib/ferry_store.dart, packages/ferry_store/lib/src/json_equals.dart, packages/ferry_store/lib/src/memory_store.dart, packages/ferry_store/lib/src/store.dart, packages/ferry_store/test/json_map_equals.dart
=> feat(ferry_store): use jsonMapEquals instead of DeepCollectionEquality().equals to avoid it's O(n^2) complexity, add distinct: param to watch() method

packages/ferry/lib/src/request_controller_typed_link.dart, packages/ferry/test/typed_links/request_controller_typed_link_test.dart
Fixes: https://github.com/gql-dart/ferry/issues/451
This PR adds `Map<OperationRequest, Stream<OperationResponse>> _cachedStreams` to `RequestControllerTypedLink`.
It is used to cache the streams from a request and reuse it for the requests with the same `requestId` or `==`.
=> fix(ferry): Re-use the same stream for multiple requests when possible

packages/ferry/lib/ferry_isolate.dart, packages/ferry/test/isolate/isolate_client_test.dart
This pull request fix #546 issue.
=> fix(ferry): Fix problem with operationRequest generated on initial request being included in response each time.

packages/ferry/pubspec.yaml, packages/ferry_cache/pubspec.yaml, packages/ferry_exec/pubspec.yaml, packages/ferry_flutter/pubspec.yaml, packages/ferry_generator/pubspec.yaml, packages/ferry_hive_store/pubspec.yaml, packages/ferry_store/pubspec.yaml, packages/normalize/pubspec.yaml
=> docs: add topics

packages/ferry_generator/CHANGELOG.md
docs(ferry_generator): fix CHANGELOG
=> docs(ferry_generator): fix CHANGELOG

packages/ferry_cache/test/test/data_change_streams_test.dart, packages/ferry_generator/lib/graphql_builder.dart, packages/ferry_generator/lib/src/codegen/fragment_req.dart, packages/ferry_generator/lib/src/codegen/operation_req.dart, packages/ferry_generator/lib/src/codegen/req.dart, packages/ferry_generator/lib/src/utils/config.dart, packages/ferry_test_graphql2/build.yaml, packages/ferry_test_graphql2/lib/fragments/__generated__/review_fragment.req.gql.dart, packages/ferry_test_graphql2/lib/mutations/__generated__/create_review.req.gql.dart, packages/ferry_test_graphql2/lib/mutations/__generated__/review_with_date_scalar.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/aliased_hero.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/hero_no_vars.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/hero_with_fragments.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/hero_with_inline_fragment.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/human_with_args.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/review_by_id.req.gql.dart, packages/ferry_test_graphql2/lib/queries/__generated__/reviews.req.gql.dart
- feat(ferry_generator)!: make dataToJson() method type safe by using the generic data type instead of dynamic. To opt-out of this new behaviour, pass `data_to_json: dynamic_param` to your build.yaml
- test(ferry_cache): fix tests to support new ferry_generator version with better type safety
=> feat(ferry_generator)!: more type safety for dataToJson()

docs/codegen.md, packages/ferry_generator/lib/graphql_builder.dart, packages/ferry_generator/lib/src/utils/config.dart, packages/ferry_generator/pubspec.yaml, packages/ferry_test_graphql2/build.yaml, packages/ferry_test_graphql2/pubspec.yaml
Hello/Hallo/Servus/Grüß Gott @knaeckeKami,
Now that https://github.com/gql-dart/gql/pull/434 is merged, I thought I'll hold true to my word and open this PR to hover up the newly introduced `vars_create_factories` option to Ferry!
This PR relies on a new version release of the `gql` package though, that still needs to be released and assumes it's going to be version 0.9.2 - let me know if you you prefer a different way of doing this.
While writing the docs for this new version, I also noticed that the new `tristate_optionals` option was missing in the docs, so I took the liberty to add that as well - hope you don't mind! 
Let me know if anything else needs to be changed! 
Thanks!
=> feat(vars-builder-generator): Adding `vars_create_factories` to ferry_generator|graphql_builder

packages/ferry_exec/lib/src/json_operation_request.dart
I forgot to pass context in `JsonOperationRequest` in #576
=> fix: pass context for JsonOperationRequests

packages/ferry_generator/lib/graphql_builder.dart, packages/ferry_generator/pubspec.yaml, packages/ferry_test_graphql2/pubspec.yaml
This is the follow up PR for https://github.com/gql-dart/gql/pull/451 to enable passing through the builder options to the schema builder so this could be used from within the `ferry_generator`.
To avoid assuming the correct version for the 'gql_code_builder` dependency, I didn't change the pubspec.yaml yet. So this might still be a todo.
Thanks!
=> feat(input-create): Passing through builder options to schema builder

packages/ferry/lib/ferry_isolate.dart
* Makes the commandSendPort visible outside of the package
* Create a new `IsolateClient.attach(SendPort)` function to attach to an existing client from a separate Isolate
=> feat(ferry): allow sharing of clients between Isolates

packages/ferry/test/isolate/isolate_client_test.dart
=> chore: fix isolate test that tests sending invalid data, since Dart is much more lenient now

docs/customization.md, packages/ferry/lib/src/add_typename_typed_link.dart, packages/ferry_generator/lib/src/utils/add_introspection.dart, packages/normalize/lib/src/denormalize_fragment.dart, packages/normalize/lib/src/denormalize_operation.dart, packages/normalize/lib/src/normalize_fragment.dart, packages/normalize/lib/src/normalize_operation.dart, packages/normalize/lib/src/utils/add_typename_visitor.dart, packages/normalize/lib/src/utils/validate_structure.dart, packages/normalize/lib/src/utils/well_known_directives.dart
This adds a const constructor to the visitors.
=> refactor(normalize,ferry,ferry_generator): Add const constructor to visitors

packages/ferry_cache/lib/src/cache.dart, packages/ferry_cache/pubspec.yaml, packages/ferry_cache/test/eviction_test.dart
allow evicting the root fields of an operation
helps with #618
=> feat(ferr_cache): add evict operation

packages/ferry/lib/ferry_isolate.dart, packages/ferry/lib/src/isolate/isolate_commands.dart, packages/ferry_cache/lib/src/cache.dart, packages/ferry_cache/pubspec.yaml, packages/ferry_cache/test/eviction_test.dart
- **feat(ferry): add evict operation to ferry isolate client**
=> feat(ferry): add evict operation to isolate client

packages/ferry_hive_ce_store/.gitignore, packages/ferry_hive_ce_store/CHANGELOG.md, packages/ferry_hive_ce_store/LICENSE, packages/ferry_hive_ce_store/README.md, packages/ferry_hive_ce_store/analysis_options.yaml, packages/ferry_hive_ce_store/lib/ferry_hive_store.dart, packages/ferry_hive_ce_store/lib/src/hive_store.dart, packages/ferry_hive_ce_store/pubspec.yaml, packages/ferry_hive_ce_store/test/operations_test.dart
initial version of ferry_hive_ce_store
=> feat(ferry_hive_ce_store): inital commit

packages/ferry/lib/src/request_controller_typed_link.dart, packages/ferry/test/typed_links/request_controller_typed_link_test.dart
Update RequestControllerTypedLink so that it will not refetch and return the stream result directly.  This allows the stream to end if the server completes the stream, and the listeners `onData` will fire.
Since the requestController stream never closes the switchMap's result stream will also never reach the onDone state.  This uses only the first matching requestController emitted request when it is a subscription operation.  This allows the switchMap's resulting stream to close when the server's response stream closes as well.
=> RequestControllerTypedLink return subscription streams that can end

docs/codegen.md, packages/ferry_generator/lib/graphql_builder.dart, packages/ferry_generator/lib/serializer_builder.dart, packages/ferry_generator/lib/src/utils/config.dart, packages/ferry_generator/lib/src/utils/writer.dart
Adds a flag to the build.xml's options to prefix the generated code with `// dart format off`.
I set the default value is true to not affect any existing output.
Do I need to make any other changes for this simple feature?
=> feat(ferry_generator): add option to disable formatting

packages/ferry_generator/lib/serializer_builder.dart, packages/ferry_generator/pubspec.yaml
- migrate serializer builder to analyzer v7 element APIs
- relax analyzer dependency range to allow >=7 <9
- not run (not requested)
=> fix: support analyzer v7 APIs
